### PR TITLE
Add support for keyboard brightness toggle and display brightness

### PR DESCRIPTION
**Pull request by denzilferreira**
This should restore the functionality of FN+Space for toggling keyboard brightness and display brightness changes.

### CODE REVIEW

**Comment by denzilferreira** [comment]
I just tested and you don't need Thinkpad Assistant after this.

**Comment by yusifsalam** [comment]
Personally I use Karabiner Elements to fix the brightness controls but I'll try this.

**Comment by denzilferreira** [comment]
Wanted a solution without having additional software to control :) now also trying to get the native microphone, bluetooth and wifi toggles to work.

D

**Comment by yusifsalam** [comment]
For some reason brightness keys only work before login for me. I've uninstalled Karabiner so not sure what's going on.

**Comment by denzilferreira** [comment]
Hum... did you install Monitor Control? Maybe something is left from Karabiner? It's working here before and after login... so must be something that runs at login for your user. Take a look at the login items at the system preferences.

**Comment by yusifsalam** [comment]
I don't have monitor control installed, so could be that? I've now disabled all login items and no luck still. Can you check if your brightness controls still work without monitor control?

**Comment by yusifsalam** [comment]
OK, it's working now, it's been Karabiner all along. I installed Karabiner again, changed my keyboard type in karabiner and removed it and now everything is fine.
Thanks for the PR!

**Comment by denzilferreira** [comment]
;)

#> sudo mail from:Denzil
#> Sent successful (elapsed .001 seconds)

**Pull request merged**
