### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by denzilferreira**
Updated to include i7, latest ACPI and kexts bundled.

### CODE REVIEW

**Review by yusifsalam — CHANGES_REQUESTED** [review]
AirportItlwm has been merged to itlwm now, so the description change is not necessary. 
CPU section reads a bit weird, should it be `Intel i5-8265U/i7-yourmodel` instead?

**Comment by denzilferreira** [comment]
CPU: Intel i7-8565U

:)

**Comment by denzilferreira** [comment]
Updated

**Review by yusifsalam — CHANGES_REQUESTED** [review]
i7-8565U is actually Whiskey Lake, as far as I'm aware we don't have any other reports of Coffee lake CPUs running this setup : )
https://ark.intel.com/content/www/us/en/ark/products/149091/intel-core-i7-8565u-processor-8m-cache-up-to-4-60-ghz.html

**Comment by denzilferreira** [comment]
Hum... maybe I’m the one needing coffee 😅

**Comment by denzilferreira** [comment]
OK, this should be alright now.

**Review by yusifsalam — APPROVED** [review]
Looks good

**Pull request merged**
