### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by denzilferreira**
- Tested Thunderbolt functionality, USB-C monitor, Netflix, Apple TV+ and FileVault, added missing kexts descriptions.
THANKS FOR THIS!

### CODE REVIEW

**Comment by yusifsalam** [comment]
Thanks Denzil, appreciate your contribution!

One change I would like to request is that you remove airport itlwm from kext descriptions, since it's just a build of itlwm, which I already have a description for. I do agree that it should probably be stated that it's a beta airport build though, so maybe just change the description for itlwm :)

**Comment by yusifsalam** [comment]
A bit unrelated but I peeped your fork and noticed you committed a gitignore for DS_Store files. I have that added to my global gitignore, which I recommend you do as well, since those files are littered everywhere on macOS.

**Comment by yusifsalam** [comment]
I forgot to ask, did you test everything with my config file or did you make any changes other than the serial?

**Comment by denzilferreira** [comment]
Exactly your config with my own serial generated. I later edited the config to remove Arch and Win10 from the menu but that’s all. You can make the edits you mentioned on the README as I would only be on my pc tomorrow now :)

#> sudo mail from:Denzil
#> Sent successful (elapsed .001 seconds)

**Comment by denzilferreira** [comment]
Forgot to say:
Personal Hotspot also works now from my iPhone, AirDrop too. I no longer have drops on my Airpods Pro either. Getting close to perfection! 

#> sudo mail from:Denzil
#> Sent successful (elapsed .001 seconds)

**Comment by yusifsalam** [comment]
> Forgot to say: Personal Hotspot also works now from my iPhone, AirDrop too. I no longer have drops on my Airpods Pro either. Getting close to perfection!

Did you build the kext from the latest commit or use the one in the release? On my machine AirDrop doesn't work on the release version kext.

**Comment by denzilferreira** [comment]
Hum... this is so strange... Yesterday, I could see my phone's personal hotspot and AirDrop between my phone and laptop. Now I can't...

**Comment by yusifsalam** [comment]
It's a known issue so I wouldn't worry about it too much, we just have to wait until a stable version of airport itlwm is released. 
(Unless you really need the hotspot feature, in which case you should revert to normal itlwm).

**Pull request merged**
